### PR TITLE
Prevent test-data insertion when running tests

### PR DESCRIPTION
**Pull request by skamoen**
This PR prevents the CommandlineRunner in Application.class from running when running tests. This removes the need to clear all repositories first, so they're not a dependency of the base integrationTest class anymore.

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Could this easily be extended for the dev-profile? I imagine something along the lines of `@Profile("dev")`

**Comment by skamoen** [comment]
Yes. You only have to set your Active Profile somewhere for that to work, but it works the same way.

**Comment by TimvdLippe** [comment]
I think it is better to do that instead since the tests then automatically do not run this method.

**Comment by skamoen** [comment]
This basically does the same thing, as tests are always run as with the "test" profile (which also takes care of the database config and such). This is a first step for the whole profile story that might as well be merged right now.

**Comment by TimvdLippe** [comment]
Yes I would prefer to do it completely in one go

**Pull request closed without merging**
