### PR TITLE
Fix consumption relation

### LINKED ISSUE #254: If a ticket consumes, and another ticket makes the same consumption, an error is thrown

### PR DESCRIPTION
**Pull request by martijn9612**
Fixes #254

### CODE REVIEW

**Comment by skamoen** [comment]
And this ladies and gentlemen, is why we have tests.

**Comment by martijn9612** [comment]
I know, this is also not live yet. Fixing this tomorrow.

**Comment by bvanderdrift** [comment]
Hijacked!

**Comment by skamoen** [comment]
LGTM

**Pull request merged**
