### PR TITLE
Codecov.io, Take 2

### PR DESCRIPTION
**Pull request by skamoen**

### CODE REVIEW

**Comment by skamoen** [comment]
I kind of like this, but it needs some tweaking in CodeCov settings to provide more useful information. Ignoring files will help with this. to be continued.

**Comment by TimvdLippe** [comment]
I think a more detailed report will be provided once master has a coverage report. Just like https://github.com/mockito/mockito/pull/389#issuecomment-207978632

**Comment by TimvdLippe** [comment]
Should be updated. If you could try a merge from master into this branch, hopefully the coverage report should include more information as it can now generate a diff between 2 diffs.

**Comment by skamoen** [comment]
I don't think this is useful enough yet. Maybe next year when we'll actually use all the code that's in it.

**Pull request closed without merging**
